/*
 * VicisCycle 2012
 * Released under GNU GPL License v2
 */
package viciscycle.gui;

import java.awt.BorderLayout;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.ResourceBundle;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;


/**
 *
 * @author roland
 */
public class GameTitleInternalFrame extends javax.swing.JInternalFrame {
	
	/**
	 * Creates new form GameTitleInternalFrame
	 */
	public GameTitleInternalFrame()  {
		super("15", false, false, false, false);
		ResourceBundle currentRes = ResourceBundle.getBundle("viciscycle.translation.lang"/*
		 * ,Locale.CHINESE
		 */);
		setTitle(currentRes.getString("viciscycle.titlePage"));
		setBounds(0, 0, 320, 300);
		setLocation((760 - 320) / 2, (560 - 300) / 2);
		JPanel gp = new JPanel();
		gp.setSize(320, 300);
		
		JButton startServerButton = new  JButton(currentRes.getString("viciscycle.startServer"));
		JButton joinGameButton = new JButton(currentRes.getString("viciscycle.joinGame"));
		JButton creditsButton = new JButton(currentRes.getString("viciscycle.credits"));
		JButton exitButton = new JButton(currentRes.getString("viciscycle.exit"));
		
		try {
			File HanWangFile = new File("font/WCL-07.ttf");
			Font HanWangFont = Font.createFont(Font.TRUETYPE_FONT, HanWangFile).deriveFont(Font.PLAIN, 18);
			
			startServerButton.setFont(HanWangFont);
			joinGameButton.setFont(HanWangFont);
			creditsButton.setFont(HanWangFont);
			exitButton.setFont(HanWangFont);
		} catch (FontFormatException|IOException e) {
		}
		
		
		
		JLabel titleLabel = new JLabel();
		titleLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viciscycle/graphics/logo.jpg"))); // NOI18N

		
		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(GroupLayout.Alignment.CENTER)
					//.addGap(100,100,100)
					.addGroup(layout.createSequentialGroup()
						.addGroup(layout.createParallelGroup()
							.addGap(100,100,100))
						.addGroup(layout.createParallelGroup()
							.addComponent(titleLabel,180,180,180)
							.addComponent(startServerButton,180,180,180)
							.addComponent(joinGameButton,180,180,180)
							.addComponent(creditsButton,180,180,180)
							.addComponent(exitButton,180,180,180)
						)
						.addGroup(layout.createParallelGroup()
							.addGap(100,100,100))
					)
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(layout.createSequentialGroup()
						.addContainerGap(50, Short.MAX_VALUE)
						.addComponent(titleLabel)
						.addGap(20,20,20)
						.addComponent(startServerButton)
						.addGap(20,20,20)
						.addComponent(joinGameButton)
						.addGap(20,20,20)
						.addComponent(creditsButton)
						.addGap(20,20,20)
						.addComponent(exitButton)
						.addContainerGap(50, Short.MAX_VALUE)
					)

				);
		/*JButton b = new JButton(currentRes.getString("viciscycle.startServer"));
		 * gp.add(b);
		 * b = new JButton(currentRes.getString("viciscycle.joinGame"));
		 * gp.add(b);
		 * b = new JButton(currentRes.getString("viciscycle.credits"));
		 * gp.add(b);
		 * b = new JButton(currentRes.getString("viciscycle.exit"));
		 * gp.add(b);
		 * add(gp, BorderLayout.CENTER);*/
		pack();
		//initComponents();
	}
	
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        jLabel1.setText("jLabel1");

        jButton2.setText("jButton2");

        jButton3.setText("jButton3");

        jButton4.setText("jButton4");

        jButton5.setText("jButton5");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viciscycle/graphics/logo.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton5)
                            .addComponent(jButton4)
                            .addComponent(jButton3)
                            .addComponent(jButton2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jLabel2)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
